### ISSUE TITLE
CSS Custom Properties

### ISSUE THREAD

**Issue by kevinSuttle** [rtfeldman/elm-css#156]
Is the recommended syntax for "CSS ~~variables~~ Custom Properties" covered by this function?

https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L5105

**Comment by lukewestby** [comment]
Can you share some more context on what the recommended syntax for CSS Custom Properties is?

**Comment by kevinSuttle** [comment]
Sure. 

Normally they're declared inside the global root selector

```css 
:root {
  --primaryThemeColor: #b4d4ss;
}

.newsfeed {
  background-color: var(--primaryThemeColor);
}
```




https://philipwalton.com/articles/why-im-excited-about-native-css-variables/
