### ISSUE TITLE
Is it possible to target child by class?

### ISSUE THREAD

**Issue by sporto** [rtfeldman/elm-css#199]
I often find the scenario where I need to target a class when on a child element when building menus and tooltips.

For example in plain Css:

```css
.tooltip {
	display: none;
}

.parent:hover .tooltip {
	display: block;
}
```

So the tooltip is shown when hovering on the parent element.

I tried something like this in elm-css:

```elm
        [ (.) ParentClass
            [ hover
                [ (.) ChildClass
                    [ display block
                    ]
                ]
            ]
        , (.) ChildClass
            [ display none ]
        ]
```

But this doesn't work. Is it possible to achieve this?
