### ISSUE TITLE
Multiple classes selector

### ISSUE THREAD

**Issue by pauldijou** [rtfeldman/elm-css#206]
I couldn't find a way to write a selector targeting several classes on the same DOM element. Here is the CSS I'm trying to produce

```css
.myClass { display: none; }
.myClass.opened { display: block; }
```

This sample is ultra simple and could be solved using inline style for the `display` property but my real use case is more complex and I would like to keep everything inside the CSS file. I can think off two solutions to solve this.

1) Having a `classes` function, just like `class` (or `(.)`) but takes a `List class` as first argument. Easy enough.

2) But the previous solution does not allow nesting. Most the time, in SASS or LESS, you would write

```less
.myClass {
  display: none;
  &.opened { display: block; } 
}
```

So, just like `children` and `descendants`, we could have a `and` or whatever name you like to have nested classes but generating the selector on the same level.

What do you think?
