### ISSUE TITLE
Validation error for classname collisions?

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#248]
Before emitting stylesheets, the `elm-css` binary could detect when you've made two class declarations that share a classname, and raise a validation error.

So this would become an error:

```css
.foo {
  display: inline-block;
  font-weight: bold;
}

.foo {
  margin: 10px;
}
```

It seems like if you ever have this situation, it would have been clearer to combine the styles into one declaration—for example, using a mixin. It seems like if you ever did this, it would have been unintentional, a namespacing mistake.

The underlying question I'm trying to answer is: **is it ever a good idea to have two different declarations in your stylesheets which style the same classname?**

**NOTE:** I'm aware that this *could* be configurable; please don't respond saying that it ought to be. 🙂

**Comment by wohanley** [comment]
I think it's a good idea sometimes. Consider something like (apologies if there's a CSS pseudocode convention I'm ignorant of):
```css
.delete-button {
  color: red;
  display: none;
}

.admin-stuff {
  visibility: hidden;
}

if admin:
  .delete-button {
    display: block;
  }

  .admin-stuff {
    visibility: visible
  }
```
It's nice to be able to combine all the changes related to one condition in one place.
