### ISSUE TITLE
Each does not keep pseudoclasses

### ISSUE THREAD

**Issue by Stijnkool** [rtfeldman/elm-css#295]
The following code:
```elm
each
    [ class Test
    , \s -> class Test [ focus s ]
    , \s -> class Test [ focus [ hover s ] ]
    ]
    [ color (hex "FF0000")
    ]
```
compiles into:
```css
.Test,
.Test,
.Test {
   color: "#FF0000";
}
```
while I think it should compile into:
```css
.Test,
.Test:focus,
.Test:focus:hover {
   color: "#FF0000";
}
```
Or am I missing something?

elm-css version: `"9.1.0 <= v < 10.0.0"`
