### ISSUE TITLE
Incorrect CSS cascade when styles compiled to attributes are mixed

### ISSUE THREAD

**Issue by Stijnkool** [rtfeldman/elm-css#337]
When having a styled element, lets say a button.
```elm
styledButton : List (Attribute msg) -> List (Html msg) -> Html msg     
styledButton =
    styled button
        [ padding (px 10)
        , border3 (px 1) solid (hex "FF0000")
        ]
```
We can use it as it is (the base version):
```elm
view : Html msg
view =
    styledButton [] [ text "a button"]
```
But what if we want to extend the styled element with some other styles.
I want to keep the original styles but increase the padding. (the extending version)
```elm
anotherView: Html msg
anotherView =
    styledButton [ css [padding (px 20)] ] [ text "a bigger button"]
```
So I am adding 2 padding rules. The last one in the outputted css will be used. But different classes are being generated for each (for the base styles and for the extending styles).

- How can elm-css guarantee that the extending class will be after the base class (the class generated by the base css on the styled element) in the final css. 
- Should elm-css guarantee it? The order of the attributes should have no meaning.
- I am running into cases where the extending class is after the base class and vice versa
- This seems like a problem inherent with mixing and matching styles compiled to attributes.
- Is this the problem to what the line _This is less flexible than mixing and matching `Style` values_ refers to?

Thanks a lot. I love the `Html.Styled` way of doing things!

**Comment by rtfeldman** [comment]
Thanks for bringing this up! Quick version of how this currently works:

* It doesn't matter how you order the attributes. You'll get the same output.
* If you use `css` attributes twice on the same element, and they both define the same property, there is no guarantee which definition will "win."

I hadn't realized this in the original design, but it's potentially easy to end up with surprising bugs from this. Like if I write the code you wrote above, and then later, I add a new property to one of the two styles, that might cause the order in which they get emitted to be flipped - which could effectively impact properties other than the one I added.

I'd be pretty surprised if that happened...I bet I wouldn't have thought to re-test those styles.

That said, it's possible to change the compiled output to make this no longer true. We could instead make it so that each subsequent attribute overrode the previous one - such that your example above would work.

To make this work, we'd have to compile to one class per declaration, the way [Styletron](https://github.com/rtsao/styletron) does. I have not looked into what the performance implications of this change would be, but Styletron [claims to be faster than the hashed-class approach](https://ryantsao.com/blog/virtual-css-with-styletron), so maybe it's a win-win.

**Comment by aleksdao** [comment]
I recently learned React Native for Web's Stylesheet also generates one class per declaration. Nicholas Gallagher shared some great insights on their Stylesheet implementation in this talk (React Rally: https://youtu.be/tFFn39lLO-U?t=997)

**Comment by mfeineis** [comment]
First things first: thank you Richard for this library, I really like this new approach for CSS in Elm. 

As of now I haven't encountered this issue but my take on this would be this: as a user of the library my expectation would be that subsequent styles would enhance/override previous ones. The fact that under the hood the subsequent CSS batches are probably kept in a flat list imho is an implementation detail, I wouldn't expect any ordering issues - the last declaration clearly wins. An example of what I mean, from this snippet:

```elm
-- A
styledButton : List (Attribute msg) -> List (Html msg) -> Html msg     
styledButton =
    styled button
        [ padding (px 10)
        , border3 (px 1) solid (hex "FF0000")
        , backgroundColor (hex "eeeeee")
        ]

-- B
customizedButton : List (Attribute msg) -> List (Html msg) -> Html msg   
customizedButton =
    styledButton 
        [ css 
            [ padding (px 5) 
            , color aliceblue
            , borderColor (hex "00FF00")
            ] 
        ] 
        [ text "My custom button" ]
```
I would expect to get something like this css with alphabetical ordering of the properties

```css
/* Ideal outcome */
.styledButtonHash {
    background-color: #EEEEEE;
    border: 1px solid #FF0000;
    padding: 10px;
}

.customizedButtonHash { 
    background-color: #EEEEEE; // Stays the same as A
    border: 1px solid #00FF00; // Merged A and B
    color: aliceblue; // Added by B
    padding: 5px; // Overwritten padding by B
}
```

I don't know exactly what the current implementation does and I realize that merging CSS declarations might be too much effort but maybe respecting the declaration ordering we could end up with:

```css
/* still Ok but a bit wasteful I guess */
.styledButtonHash {
    background-color: #EEEEEE;
    border: 1px solid #FF0000;
    padding: 10px;
}

.customizedButtonHash { 
    background-color: #EEEEEE; // From A
    border: 1px solid #FF0000; // From A
    border-color: #00FF00; // From B
    color: aliceblue; // From B
    padding: 10px; // From A
    padding: 5px; // From B
}
```
although that might be somewhat confusing on inspection and is more text for the browser to parse.
