### ISSUE TITLE
Nested selectors not working

### ISSUE THREAD

**Issue by azer** [rtfeldman/elm-css#430]
Selectors allow us create keyframes theoretically, but we're not able to create nested selectors.

For example, following code;

```elm
selector "@keyframes sk-bouncedelay"
            [ descendants
                [ selector "0%, 80%, 100%"
                    [ property "transform" "scale(0)" ]
                , selector "40%"
                    [ property "transform" "scale(1.0)" ]
                ]
            ]
```

Outputs: 

```css
@keyframes sk-bouncedelay  0%, 80%, 100% {
    transform: scale(0);
}

@keyframes sk-bouncedelay  40% {
    transform: scale(1.0);
}
```

Instead of;

```css
 @keyframes sk-bouncedelay {
    0%, 80%, 100% { 
      transform: scale(0);
    } 40% { 
      transform: scale(1.0);
    }
  }
```
