### ISSUE TITLE
Add comment support for compatibility with style guide generators

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#51]
http://trulia.github.io/hologram/

One possible API: add a `comment` function that emits comments.

``` elm
stylesheet
  { name = "homepage" }
  [ comment
"""doc

---
title: Buttons
name: button
category: Base CSS

---

Button styles can be applied to any element.
"""
  , ((.) Button)
      [ borderColor (rgb 12 120 10) ]
  ]
```

...outputs:

``` css
/*doc

---
title: Buttons
name: button
category: Base CSS

---

Button styles can be applied to any element.
*/
.homepageButton {
    border-color: rgb(12, 120, 10);
}
```

Supporting this would require changing `Declarations` to support `Comment`.
