### ISSUE TITLE
`<span> > <style>` wrapping in elm-css 17 has unexpected side effect inside grid container

### ISSUE THREAD

**Issue by ymtszw** [rtfeldman/elm-css#557]
In elm-css 17.0.1, `<style>` is wrapped in `<span>` to guard against some browser extension mess-ups.
The intention is good but it has unexpected side effect inside grid container.

SSCCE: https://ellie-app.com/g3z4zCTShLfa1

This example uses following style on container `div`:

```css
._5c4fac34 {
    position:fixed;
    top:0px;
    right:0px;
    bottom:0px;
    left:0px;
    width:100%;
    height:100%;
    display:grid;
    align-items:center;
    justify-items:center;
}
```

This is a convenient "just stay center!" container style, which can horizontally/vertically center its direct child via `align/justify-items: center`.

We were using this for creating "backdrop" area of modal dialogs and working pretty well.

However with elm-css 17.0.1, such container now hosts an additional child which is `<span>` containing style node, and that `<span>` now takes up a portion of the grid container since it is (at a glance from grid container) an ordinary element!

Screenshot from SSCCE:

![image](https://user-images.githubusercontent.com/4507126/144844407-ed181d97-206b-4ffc-9cdc-ab237ba772cf.png)

A quick workaround is to put `display: none;` to wrapping `<span>`s. At least it works for this particular example, tested from dev console:

![image](https://user-images.githubusercontent.com/4507126/144845577-e3b64daa-09c4-44f1-9359-9c49247a4481.png)
