### ISSUE TITLE
Parent rule gets printed one time for each rule in its `children`

### ISSUE THREAD

**Issue by klaftertief** [rtfeldman/elm-css#99]
That means the generated CSS can have multiple identical rules.

E.g. 

```Elm
    article
        [ margin zero
        , children
            [ header [ margin zero ]
            , section [ margin zero ]
            , nav [ margin zero ]
            ]
        ]
```

gets compiled to

```Css
article {
    margin: 0;
}

article > header {
    margin: 0;
}

article {
    margin: 0;
}

article > section {
    margin: 0;
}

article {
    margin: 0;
}

article > nav {
    margin: 0;
}
```

Is this expected behaviour? One could fix the CSS by splitting the parent in one definition with just the styles and one with just the children. Or would there be a more idiomatic way?
